import subprocess
from pathlib import Path


def command_output(command, cwd):
    completed = subprocess.run(command, cwd=cwd, text=True, capture_output=True)
    return completed.stdout.strip() if completed.returncode == 0 else "unavailable"


def main():
    repo_root = Path(__file__).resolve().parents[1]
    output = repo_root / "results" / "reproducibility_manifest.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    commit = command_output(["git", "rev-parse", "HEAD"], repo_root)
    text = f"""# CWVIG-OSD Reproducibility Manifest

- Generated by: Codex
- Generated from git commit: `{commit}`
- Refresh command: `C:\\Windows\\py.exe -3 scripts\\write_reproducibility_manifest.py`
- Selected default candidate preset: `capped`
- Frozen config: `configs/cwvig_presets/capped_default.json`

## Build Commands

```powershell
cmake -S benchmark/flyki_overlap -B build/flyki -DCMAKE_BUILD_TYPE=Release
cmake --build build/flyki --target cwvig_grouping_pipeline_cli --config Release
cmake --build build/flyki --target grouping_source_cli --config Release
```

## Experiment Commands

```powershell
scripts\\run_grouping_smoke.ps1
scripts\\run_grouping_medium.ps1
C:\\Windows\\py.exe -3 experiments\\check_reproducibility.py --clean
```

## Expected Output Files

- `results/repro_smoke/summary.csv`
- `results/repro_smoke/preset_summary.csv`
- `results/repro_smoke/default_preset_selection.md`
- `results/repro_medium/summary.csv`
- `results/repro_medium/preset_summary.csv`
- `results/repro_medium/default_preset_selection.md`
- `results/repro_checks/fixed_a/predicted_groups.txt`
- `results/repro_checks/fixed_a/predicted_overlap.txt`

## Evidence Scope

- Freeze decision uses Phase 5C medium grouping evidence.
- Covered benchmark scope: Flyki `func=1`, `dimension_limit=10,20,50`, seeds `1,3,5,11`, contexts `3,5`.
- This is a current default candidate for grouping experiments, not a final full-benchmark optimizer default.

## Known Blocker

The original external CMA-ES files are still missing, so the full `cbocco` target remains unavailable. Phase 5D does not require CMA-ES and does not modify optimization logic.
"""
    output.write_text(text, encoding="utf-8")
    print(output)


if __name__ == "__main__":
    main()
